# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc993fb2f233170166c7af5c5a5d764627bf0da8d531bc4e91316a38ad1e726e78f8b5956d81d409f30a7a26f98831694e393b288c181500df46ecfdeb0139d6

test:
  secret_key_base: 87b2fc6712cda7397b6be63eea81c090b718eebe4bd6c6c60b0a60c1c4f19ea7a5a3baef395a9eb12918086078a2a62f4a446ab463b2ccde3eeac4103d8bc1e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
